### ISSUE TITLE
问下，显示详情的功能

### ISSUE THREAD

**Issue by grHand** [Shaman05/wxCharts#1]
看到文档说正在开发点击显示详情的功能，现在有进展吗？有这个需要，如果作者快的话，就不改动您的源码了。。

**Comment by Shaman05** [comment]
@grHand 是指触摸移动显示详情吗？
之前有做过一个版本，我用的思路是再加一个canvas盖在两个基础图形canvas的上面，但是手势移动的时候坐标线的移动有点卡，由于手头有事情，目前还没有新的进展。

**Comment by grHand** [comment]
@Shaman05 是的，唉，手头有个项目着急要实现这个，直接改源码又有点麻烦。

**Comment by Shaman05** [comment]
这个是扩展，不需要改现有，只需要增加，配置项里可能需要一点改动。

**Comment by grHand** [comment]
@Shaman05 能说下你开发触摸显示详情的思路吗？  我参考下开发下这块的功能。

**Comment by Shaman05** [comment]
@grHand 在现有的canvas区域上再覆盖一个canvas层用来绘制手势移动时候的坐标轴和数值显示，具体的实现思路你可以这么做： 用touchstart事件来开启坐标的显示，touchmove来监听手势移动位置，并计算当前位置在坐标轴的实际位置，根据结果来确定x,y两根线对应的数据，K线的话你需要额外处理x轴的移动，它应该是按你x轴的单位移动。

**Comment by Shaman05** [comment]
@grHand 开启坐标的显示你可以做成长按（longtap）2秒或3秒后左边才显示，坐标轴显示后，才处理 touchmove

**Comment by Shaman05** [comment]
@grHand 中午简单的加了这个效果（readme最底部有演示图），开发者工具不是很流畅，但是真机上还是很流畅得。没有处理数据显示，这个你自己可以加吧。
新增的模块文件：[axis-show.js](https://github.com/Shaman05/wxCharts/blob/master/utils/wxChart/axis-show.js)
