### ISSUE TITLE
期待大神的数据接口说明

### ISSUE THREAD

**Issue by yaotaiye** [Shaman05/wxCharts#2]
说明文档还是少了点呀

**Comment by yaotaiye** [comment]
![b 8a s rqkouo wbe6u2](https://user-images.githubusercontent.com/24998871/27465944-64defc34-5809-11e7-877a-3cef1f3f9c02.png)
就是画红线的地方代表什么呀

**Comment by Shaman05** [comment]
已添加相关文档： [数据字段说明](https://github.com/Shaman05/wxCharts/wiki/%E6%95%B0%E6%8D%AE%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E)
