### ISSUE TITLE
请问k线蜡烛图如何配置x轴的时间

### ISSUE THREAD

**Issue by jacksplwxy** [Shaman05/wxCharts#4]

**Comment by Shaman05** [comment]
已添加了K线配置文件时间的说明，[这里](https://github.com/Shaman05/wxCharts/wiki/K%E7%BA%BF%E5%9B%BE%E9%85%8D%E7%BD%AE2%EF%BC%88%E6%88%90%E4%BA%A4%E9%87%8F%EF%BC%89)

**Comment by Shaman05** [comment]
具体获取方法还是要看数据的定义，我这里获取起止时间是在 [这里](https://github.com/Shaman05/wxCharts/blob/master/utils/wxChart/k-line.js) metadata2方法里的startTime和endTime
