### ISSUE TITLE
分时数据量大于5天的疑问

### ISSUE THREAD

**Issue by ghost** [Shaman05/wxCharts#5]
demo里分时最多能显示5天，请问如果要显示半年的数据量，这个框架该怎么扩展或操作，能否给点思路，thx！

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/7418617/31992960-62434630-b941-11e7-8621-7ecf65cdf78a.png)
请问像截图那样要显示一年的数据量该如何操作，能否给点思路蟹蟹啦！

**Comment by Shaman05** [comment]
不好意思这段时间一直太忙没太关注github。
半年的数据显示只要数据是半年的即可，在分时图的 time-sharing.js 里的metadata1和metadata2方法里 dataStore.axis.day5 = common.disRepArr(day5) 就是处理数据的地方。

**Comment by ghost** [comment]
灰常感谢。。你五天数据是this.unit乘以5的
if (options.name == 'time-sharing-5day') {
        this.unit = this.unit * 5;
   }
如果是半年数据难道this.unit要乘以180天吗？因为半年的数据量太多了，如果不乘180的话，只能显示前面5天数据。如果乘以180感觉也不合理，太多数据要渲染推测应该就会很卡。这种情况改怎么处理呢请问？

**Comment by Shaman05** [comment]
首先this.unit是控制x轴显示多少个单位的，如果要显示半年的分时图，即180天，首先应该是你确认X轴到底你要展示多少个单位（this.unit），再从数据上处理你180天的数据，转化成对应条数据。比如：180天，每天是240条，如果this.unit就按天为单位（即X轴是180个单位），那你就是将每天240条取一个平均值，做为要展示180天数据的第一项。如果this.unit是按半天为单位（即X轴是360个单位），那你就是将每天前的120条作为360个单位的第一项，后120条作为第二项，以此类推。
说到底就是取决与你的 this.unit 是多少，再处理对应数据，目前我DEMO是只针对某天的分时图（this.unit=240）和5日分时（this.unit = 240*5）做了处理。

**Comment by Shaman05** [comment]
因为这个是固定给分时图用的，单日分时固定就是240条数据，我就是展示240个单位，五日分时我直接就是展示 240*5 个单位（还不会触及性能问题），所以没有做任何处理。
你的情况应该根据你实际需要，确定this.unit 再处理数据，逻辑的话可以参照上面说的。

**Comment by ghost** [comment]
好的。。谢谢指教。祝生活愉快，好人多福~..~
