### ISSUE TITLE
pricedigit配置在什么地方才会生效？？？

### ISSUE THREAD

**Issue by chenqgp** [Shaman05/wxCharts#7]
storage.js里的price digit我试过了没有用，在kl.js里面应该如何配置呢？？？？？？

**Comment by chenqgp** [comment]
@Shaman05

**Comment by Jedore** [comment]
请问 shaman05 :+1: k-line.js中的historyStep变量有什么意义

**Comment by Shaman05** [comment]
@chenqidage storage.js只是模拟数据，pricedigit这个参数绘图中没有使用。

**Comment by Shaman05** [comment]
@Jedore historyStep这个是在metadata方法里的，这个方法是转化绘图数据，我这里是根据storage.js的模拟数据来实现这个metadata方法的转化逻辑，在我这个里面historyStep是指均线最大日期值（20），这个是用来获取计算均线数据所需的历史数据。
